title: Sticks & Steaks
description: "don't threaten us with a good time"
url: "https://sticksandsteaks.com"
baseurl: ""
permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
